<a href="https://colab.research.google.com/github/SnehaJainM/Scientific-Computing-Using-Python/blob/main/Numpy_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy

In [3]:
numpy_array = numpy.array([33,19,2,3,4])

In [ ]:
numpy_array
#array([33, 19,  2,  3,  4])

array([33, 19,  2,  3,  4])

*Numpy arrays*


*   homogenous collection
*   if heterogrenous is passed it converts into the datatype in the given array
*   List to List  operations cannot be performed multiplying two lists for ex






In [ ]:
numpy_array1 = numpy.array([33,19,2,3,4,'hello'])

In [ ]:
numpy_array1
#all ele are converted to string
 ]
numpy_array1
#all ele are converted to string
# array(['33', '19', '2', '3', '4', 'hello'], dtype='<U21')

array(['33', '19', '2', '3', '4', 'hello'], dtype='<U21')

In [ ]:
numpy_array2 = numpy.array([33,19,2,3,4.5,'hello'])
numpy_array2
#all ele are converted to str
# array(['33', '19', '2', '3', '4.5', 'hello'], dtype='<U32')

array(['33', '19', '2', '3', '4.5', 'hello'], dtype='<U32')

In [ ]:
numpy_array2 = numpy.array([33,19,2,3,4.5])
numpy_array2
#all ele are converted to float
# array([33. , 19. ,  2. ,  3. ,  4.5])

array([33. , 19. ,  2. ,  3. ,  4.5])

In [ ]:
# numpy_array2 = numpy.array([33,19,2,[3,5]])
numpy_array2
# gives an error because single elements cannot be converted into lists
# array([33. , 19. ,  2. ,  3. ,  4.5])

array([33. , 19. ,  2. ,  3. ,  4.5])

In [ ]:
numpy_array2 = numpy.array([33,19,2,3,{8,9,'what'}])
numpy_array2
numpy_dict_array=numpy.array(('yay',2,3,{4,5}))
numpy_dict_array
#sets and dictionaries are considered as objects thus no type conversions are done.
# when you try to access to objects the last object is returned by the control. so use a print() if you want to run both and display them.
# array(['yay', 2, 3, {4, 5}], dtype=object)

array(['yay', 2, 3, {4, 5}], dtype=object)

In [ ]:
numpy_complex_arr =numpy.array((1+4j,2,3,4,5))
numpy_complex_arr
#complex conversions are done.
# array([1.+4.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

array([1.+4.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

30.1.2025
1. type(arr)

2. ndim
3. shape
4. reshape(r,c)
5. flatten()
6. arange(st,stop,jump)



In [ ]:
arr_dim = numpy.array([1,2,3,4,5])
arr_dim
# array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
type(arr_dim)

numpy.ndarray

nd means ndimensional array to check the dimensions we use the attribute ndim.

In [ ]:
arr_dim.ndim
# 1

1

shape gives the rows and cols. (rows,cols)
if the number of rows is 1 then it returns (cols,)

In [ ]:
arr_dim.shape
# (5,)

(5,)

In [ ]:
arr_dim.reshape(5,1) # reshape to 5 rows
# array([[1],
#        [2],
#        [3],
#        [4],
#        [5]])

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
arr_dim2d=numpy.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_dim2d
# array([[ 1,  2,  3,  4,  5],
      #  [ 6,  7,  8,  9, 10]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr_dim2d.ndim
# 2

2

In [ ]:
arr_dim2d.shape

(2, 5)

In [ ]:
# arr_dim2d.reshape(1,7)
#raises an error as the product should be equal to the number of total elements in the entire array
arr_dim2d.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
arr_dim2d.reshape(1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
arr_dim2d.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr_dim2d.flatten('A')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

arange() similar to range but iterates over floats , complex, integer but not str

In [ ]:
arr_ = numpy.arange(1,20,2)
arr_


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
arr_float = numpy.arange(1,40,2.5)
arr_float
#array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5, 21. , 23.5, 26. ,28.5, 31. , 33.5, 36. , 38.5])

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5, 21. , 23.5, 26. ,
       28.5, 31. , 33.5, 36. , 38.5])

In [ ]:
# arr_str=numpy.arange('aanz')
# arr_str


**31.01.2025**
*  dtype  to store elements of a particular type.
7. linspace(start,stop,number_of_elements)
8. zeros((r,c))
9. ones((r,c))
10. full((r,c),value)
11. full_like(reference_variable_of_shape,value)
12. identity(number)


In [8]:
linspace_array = numpy.linspace(1,5,3)
linspace_array
#array([1., 3., 5.])


array([ 1. , 10.5, 20. ])

In [7]:
linspace_array = numpy.linspace(0,1,10,dtype='int')
linspace_array
#array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [9]:
linspace_array= numpy.linspace(1,88)
linspace_array #gens fifty elements by default
# #array([ 1.        ,  2.7755102 ,  4.55102041,  6.32653061,  8.10204082,
#         9.87755102, 11.65306122, 13.42857143, 15.20408163, 16.97959184,
#        18.75510204, 20.53061224, 22.30612245, 24.08163265, 25.85714286,
#        27.63265306, 29.40816327, 31.18367347, 32.95918367, 34.73469388,
#        36.51020408, 38.28571429, 40.06122449, 41.83673469, 43.6122449 ,
#        45.3877551 , 47.16326531, 48.93877551, 50.71428571, 52.48979592,
#        54.26530612, 56.04081633, 57.81632653, 59.59183673, 61.36734694,
#        63.14285714, 64.91836735, 66.69387755, 68.46938776, 70.24489796,
#        72.02040816, 73.79591837, 75.57142857, 77.34693878, 79.12244898,
#        80.89795918, 82.67346939, 84.44897959, 86.2244898 , 88.        ])

array([ 1.        ,  2.7755102 ,  4.55102041,  6.32653061,  8.10204082,
        9.87755102, 11.65306122, 13.42857143, 15.20408163, 16.97959184,
       18.75510204, 20.53061224, 22.30612245, 24.08163265, 25.85714286,
       27.63265306, 29.40816327, 31.18367347, 32.95918367, 34.73469388,
       36.51020408, 38.28571429, 40.06122449, 41.83673469, 43.6122449 ,
       45.3877551 , 47.16326531, 48.93877551, 50.71428571, 52.48979592,
       54.26530612, 56.04081633, 57.81632653, 59.59183673, 61.36734694,
       63.14285714, 64.91836735, 66.69387755, 68.46938776, 70.24489796,
       72.02040816, 73.79591837, 75.57142857, 77.34693878, 79.12244898,
       80.89795918, 82.67346939, 84.44897959, 86.2244898 , 88.        ])

In [11]:
linspace_array=numpy.linspace(-50,-25)
linspace_array

array([-50.        , -49.48979592, -48.97959184, -48.46938776,
       -47.95918367, -47.44897959, -46.93877551, -46.42857143,
       -45.91836735, -45.40816327, -44.89795918, -44.3877551 ,
       -43.87755102, -43.36734694, -42.85714286, -42.34693878,
       -41.83673469, -41.32653061, -40.81632653, -40.30612245,
       -39.79591837, -39.28571429, -38.7755102 , -38.26530612,
       -37.75510204, -37.24489796, -36.73469388, -36.2244898 ,
       -35.71428571, -35.20408163, -34.69387755, -34.18367347,
       -33.67346939, -33.16326531, -32.65306122, -32.14285714,
       -31.63265306, -31.12244898, -30.6122449 , -30.10204082,
       -29.59183673, -29.08163265, -28.57142857, -28.06122449,
       -27.55102041, -27.04081633, -26.53061224, -26.02040816,
       -25.51020408, -25.        ])

In [13]:
zero_array = numpy.zeros((1,1))
zero_array
#array([[0.]])
zero_array = numpy.zeros((1,5))
zero_array
# array([[0., 0., 0., 0., 0.]])

array([[0., 0., 0., 0., 0.]])

In [14]:
ones_array = numpy.ones((5,5))
ones_array
# array([[1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.],
      #  [1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
full_array=numpy.full((2,3),10202)
full_array
# array([[10202, 10202, 10202],
      #  [10202, 10202, 10202]])

array([[10202, 10202, 10202],
       [10202, 10202, 10202]])

In [20]:
full_like_array = numpy.full_like(full_array,330678)
full_like_array #array([[330678, 330678, 330678],
                     #  [330678, 330678, 330678]])
full_array # array([[10202, 10202, 10202],
                  # [10202, 10202, 10202]])

array([[330678, 330678, 330678],
       [330678, 330678, 330678]])

In [21]:
arr_empty=numpy.array(())
arr_empty
#array([], dtype=float64)

array([], dtype=float64)

In [23]:
arr_like_empty = numpy.full_like(arr_empty,1000)
arr_like_empty
#array([], dtype=float64)

array([], dtype=float64)

In [25]:
identity_matrix= numpy.identity(5,dtype='int')
identity_matrix
#array([[1., 0., 0., 0., 0.],
      #  [0., 1., 0., 0., 0.],
      #  [0., 0., 1., 0., 0.],
      #  [0., 0., 0., 1., 0.],
      #  [0., 0., 0., 0., 1.]])

# # array([[1, 0, 0, 0, 0],
#        [0, 1, 0, 0, 0],
#        [0, 0, 1, 0, 0],
#        [0, 0, 0, 1, 0],
#        [0, 0, 0, 0, 1]])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])