<a href="https://colab.research.google.com/github/SnehaJainM/Scientific-Computing-Using-Python/blob/main/Numpy_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy

In [3]:
numpy_array = numpy.array([33,19,2,3,4])

In [4]:
numpy_array

array([33, 19,  2,  3,  4])

*Numpy arrays*


*   homogenous collection
*   if heterogrenous is passed it converts into the datatype in the given array
*   List to List  operations cannot be performed multiplying two lists for ex






In [5]:
numpy_array1 = numpy.array([33,19,2,3,4,'hello'])

In [6]:
numpy_array1
#all ele are converted to string

array(['33', '19', '2', '3', '4', 'hello'], dtype='<U21')

In [7]:
numpy_array2 = numpy.array([33,19,2,3,4.5,'hello'])
numpy_array2
#all ele are converted to str

array(['33', '19', '2', '3', '4.5', 'hello'], dtype='<U32')

In [8]:
numpy_array2 = numpy.array([33,19,2,3,4.5])
numpy_array2
#all ele are converted to float

array([33. , 19. ,  2. ,  3. ,  4.5])

In [9]:
# numpy_array2 = numpy.array([33,19,2,[3,5]])
numpy_array2
# gives an error because single elements cannot be converted into lists

array([33. , 19. ,  2. ,  3. ,  4.5])

In [10]:
numpy_array2 = numpy.array([33,19,2,3,{8,9,'what'}])
numpy_array2
numpy_dict_array=numpy.array(('yay',2,3,{4,5}))
numpy_dict_array
#sets and dictionaries are considered as objects thus no type conversions are done.
# when you try to access to objects the last object is returned by the control. so use a print() if you want to run both and display them.

array(['yay', 2, 3, {4, 5}], dtype=object)

In [11]:
numpy_complex_arr =numpy.array((1+4j,2,3,4,5))
numpy_complex_arr
#complex conversions are done.

array([1.+4.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

30.1.2025
1. type(arr)

2. ndim
3. shape
4. reshape(r,c)



In [13]:
arr_dim = numpy.array([1,2,3,4,5])
arr_dim

array([1, 2, 3, 4, 5])

In [21]:
type(arr_dim)

numpy.ndarray

nd means ndimensional array to check the dimensions we use the attribute ndim.

In [14]:
arr_dim.ndim

1

shape gives the rows and cols. (rows,cols)
if the number of rows is 1 then it returns (cols,)

In [15]:
arr_dim.shape

(5,)

In [16]:
arr_dim.reshape(5,1) # reshape to 5 rows

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [18]:
arr_dim2d=numpy.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_dim2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
arr_dim2d.ndim

2

In [20]:
arr_dim2d.shape

(2, 5)

In [23]:
# arr_dim2d.reshape(1,7)
#raises an error as the product should be equal to the number of total elements in the entire array
arr_dim2d.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [24]:
arr_dim2d.reshape(1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [25]:
arr_dim2d.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
arr_dim2d.flatten('A')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

arange() similar to range but iterates over floats , complex, integer but not str

In [34]:
arr_ = numpy.arange(1,20,2)
arr_


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [35]:
arr_float = numpy.arange(1,40,2.5)
arr_float

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5, 21. , 23.5, 26. ,
       28.5, 31. , 33.5, 36. , 38.5])

In [40]:
# arr_str=numpy.arange('aanz')
# arr_str