<a href="https://colab.research.google.com/github/SnehaJainM/Scientific-Computing-Using-Python/blob/main/Numpy_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

In [2]:
numpy_array = numpy.array([33,19,2,3,4])

In [3]:
numpy_array

array([33, 19,  2,  3,  4])

*Numpy arrays*


*   homogenous collection
*   if heterogrenous is passed it converts into the datatype in the given array
*   List to List  operations cannot be performed multiplying two lists for ex






In [4]:
numpy_array1 = numpy.array([33,19,2,3,4,'hello'])

In [5]:
numpy_array1
#all ele are converted to string

array(['33', '19', '2', '3', '4', 'hello'], dtype='<U21')

In [7]:
numpy_array2 = numpy.array([33,19,2,3,4.5,'hello'])
numpy_array2
#all ele are converted to str

array(['33', '19', '2', '3', '4.5', 'hello'], dtype='<U32')

In [8]:
numpy_array2 = numpy.array([33,19,2,3,4.5])
numpy_array2
#all ele are converted to float

array([33. , 19. ,  2. ,  3. ,  4.5])

In [10]:
# numpy_array2 = numpy.array([33,19,2,[3,5]])
numpy_array2
# gives an error because single elements cannot be converted into lists

array([33. , 19. ,  2. ,  3. ,  4.5])

In [12]:
numpy_array2 = numpy.array([33,19,2,3,{8,9,'what'}])
numpy_array2
numpy_dict_array=numpy.array(('yay',2,3,{4,5}))
numpy_dict_array
#sets and dictionaries are considered as objects thus no type conversions are done.
# when you try to access to objects the last object is returned by the control. so use a print() if you want to run both and display them.

array(['yay', 2, 3, {4, 5}], dtype=object)

In [14]:
numpy_complex_arr =numpy.array((1+4j,2,3,4,5))
numpy_complex_arr
#complex conversions are done.

array([1.+4.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])