<a href="https://colab.research.google.com/github/SnehaJainM/Scientific-Computing-Using-Python/blob/main/Numpy_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

In [ ]:
numpy_array = numpy.array([33,19,2,3,4])

In [ ]:
numpy_array
#array([33, 19,  2,  3,  4])

array([33, 19,  2,  3,  4])

*Numpy arrays*


*   homogenous collection
*   if heterogrenous is passed it converts into the datatype in the given array
*   List to List  operations cannot be performed multiplying two lists for ex






In [ ]:
numpy_array1 = numpy.array([33,19,2,3,4,'hello'])

In [ ]:
numpy_array1
#all ele are converted to string
 ]
numpy_array1
#all ele are converted to string
# array(['33', '19', '2', '3', '4', 'hello'], dtype='<U21')

array(['33', '19', '2', '3', '4', 'hello'], dtype='<U21')

In [ ]:
numpy_array2 = numpy.array([33,19,2,3,4.5,'hello'])
numpy_array2
#all ele are converted to str
# array(['33', '19', '2', '3', '4.5', 'hello'], dtype='<U32')

array(['33', '19', '2', '3', '4.5', 'hello'], dtype='<U32')

In [ ]:
numpy_array2 = numpy.array([33,19,2,3,4.5])
numpy_array2
#all ele are converted to float
# array([33. , 19. ,  2. ,  3. ,  4.5])

array([33. , 19. ,  2. ,  3. ,  4.5])

In [ ]:
# numpy_array2 = numpy.array([33,19,2,[3,5]])
numpy_array2
# gives an error because single elements cannot be converted into lists
# array([33. , 19. ,  2. ,  3. ,  4.5])

array([33. , 19. ,  2. ,  3. ,  4.5])

In [ ]:
numpy_array2 = numpy.array([33,19,2,3,{8,9,'what'}])
numpy_array2
numpy_dict_array=numpy.array(('yay',2,3,{4,5}))
numpy_dict_array
#sets and dictionaries are considered as objects thus no type conversions are done.
# when you try to access to objects the last object is returned by the control. so use a print() if you want to run both and display them.
# array(['yay', 2, 3, {4, 5}], dtype=object)

array(['yay', 2, 3, {4, 5}], dtype=object)

In [ ]:
numpy_complex_arr =numpy.array((1+4j,2,3,4,5))
numpy_complex_arr
#complex conversions are done.
# array([1.+4.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

array([1.+4.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

30.1.2025
1. type(arr)

2. ndim
3. shape
4. reshape(r,c)
5. flatten()
6. arange(st,stop,jump)



In [ ]:
arr_dim = numpy.array([1,2,3,4,5])
arr_dim
# array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
type(arr_dim)

numpy.ndarray

nd means ndimensional array to check the dimensions we use the attribute ndim.

In [ ]:
arr_dim.ndim
# 1

1

shape gives the rows and cols. (rows,cols)
if the number of rows is 1 then it returns (cols,)

In [ ]:
arr_dim.shape
# (5,)

(5,)

In [ ]:
arr_dim.reshape(5,1) # reshape to 5 rows
# array([[1],
#        [2],
#        [3],
#        [4],
#        [5]])

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
arr_dim2d=numpy.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_dim2d
# array([[ 1,  2,  3,  4,  5],
      #  [ 6,  7,  8,  9, 10]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr_dim2d.ndim
# 2

2

In [ ]:
arr_dim2d.shape

(2, 5)

In [ ]:
# arr_dim2d.reshape(1,7)
#raises an error as the product should be equal to the number of total elements in the entire array
arr_dim2d.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
arr_dim2d.reshape(1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
arr_dim2d.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr_dim2d.flatten('A')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

arange() similar to range but iterates over floats , complex, integer but not str

In [ ]:
arr_ = numpy.arange(1,20,2)
arr_


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
arr_float = numpy.arange(1,40,2.5)
arr_float
#array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5, 21. , 23.5, 26. ,28.5, 31. , 33.5, 36. , 38.5])

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5, 21. , 23.5, 26. ,
       28.5, 31. , 33.5, 36. , 38.5])

In [ ]:
# arr_str=numpy.arange('aanz')
# arr_str


**31.01.2025**
*  dtype  to store elements of a particular type.
7. linspace(start,stop,number_of_elements)
8. zeros((r,c))
9. ones((r,c))
10. full((r,c),value)
11. full_like(reference_variable_of_shape,value)
12. identity(number)


In [ ]:
linspace_array = numpy.linspace(1,5,3)
linspace_array
#array([1., 3., 5.])


array([ 1. , 10.5, 20. ])

In [ ]:
linspace_array = numpy.linspace(0,1,10,dtype='int')
linspace_array
#array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
linspace_array= numpy.linspace(1,88)
linspace_array #gens fifty elements by default
# #array([ 1.        ,  2.7755102 ,  4.55102041,  6.32653061,  8.10204082,
#         9.87755102, 11.65306122, 13.42857143, 15.20408163, 16.97959184,
#        18.75510204, 20.53061224, 22.30612245, 24.08163265, 25.85714286,
#        27.63265306, 29.40816327, 31.18367347, 32.95918367, 34.73469388,
#        36.51020408, 38.28571429, 40.06122449, 41.83673469, 43.6122449 ,
#        45.3877551 , 47.16326531, 48.93877551, 50.71428571, 52.48979592,
#        54.26530612, 56.04081633, 57.81632653, 59.59183673, 61.36734694,
#        63.14285714, 64.91836735, 66.69387755, 68.46938776, 70.24489796,
#        72.02040816, 73.79591837, 75.57142857, 77.34693878, 79.12244898,
#        80.89795918, 82.67346939, 84.44897959, 86.2244898 , 88.        ])

array([ 1.        ,  2.7755102 ,  4.55102041,  6.32653061,  8.10204082,
        9.87755102, 11.65306122, 13.42857143, 15.20408163, 16.97959184,
       18.75510204, 20.53061224, 22.30612245, 24.08163265, 25.85714286,
       27.63265306, 29.40816327, 31.18367347, 32.95918367, 34.73469388,
       36.51020408, 38.28571429, 40.06122449, 41.83673469, 43.6122449 ,
       45.3877551 , 47.16326531, 48.93877551, 50.71428571, 52.48979592,
       54.26530612, 56.04081633, 57.81632653, 59.59183673, 61.36734694,
       63.14285714, 64.91836735, 66.69387755, 68.46938776, 70.24489796,
       72.02040816, 73.79591837, 75.57142857, 77.34693878, 79.12244898,
       80.89795918, 82.67346939, 84.44897959, 86.2244898 , 88.        ])

In [ ]:
linspace_array=numpy.linspace(-50,-25)
linspace_array

array([-50.        , -49.48979592, -48.97959184, -48.46938776,
       -47.95918367, -47.44897959, -46.93877551, -46.42857143,
       -45.91836735, -45.40816327, -44.89795918, -44.3877551 ,
       -43.87755102, -43.36734694, -42.85714286, -42.34693878,
       -41.83673469, -41.32653061, -40.81632653, -40.30612245,
       -39.79591837, -39.28571429, -38.7755102 , -38.26530612,
       -37.75510204, -37.24489796, -36.73469388, -36.2244898 ,
       -35.71428571, -35.20408163, -34.69387755, -34.18367347,
       -33.67346939, -33.16326531, -32.65306122, -32.14285714,
       -31.63265306, -31.12244898, -30.6122449 , -30.10204082,
       -29.59183673, -29.08163265, -28.57142857, -28.06122449,
       -27.55102041, -27.04081633, -26.53061224, -26.02040816,
       -25.51020408, -25.        ])

In [ ]:
zero_array = numpy.zeros((1,1))
zero_array
#array([[0.]])
zero_array = numpy.zeros((1,5))
zero_array
# array([[0., 0., 0., 0., 0.]])

array([[0., 0., 0., 0., 0.]])

In [ ]:
ones_array = numpy.ones((5,5))
ones_array
# array([[1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.],
      #  [1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
full_array=numpy.full((2,3),10202)
full_array
# array([[10202, 10202, 10202],
      #  [10202, 10202, 10202]])

array([[10202, 10202, 10202],
       [10202, 10202, 10202]])

In [ ]:
full_like_array = numpy.full_like(full_array,330678)
full_like_array #array([[330678, 330678, 330678],
                     #  [330678, 330678, 330678]])
full_array # array([[10202, 10202, 10202],
                  # [10202, 10202, 10202]])

array([[330678, 330678, 330678],
       [330678, 330678, 330678]])

In [ ]:
arr_empty=numpy.array(())
arr_empty
#array([], dtype=float64)

array([], dtype=float64)

In [ ]:
arr_like_empty = numpy.full_like(arr_empty,1000)
arr_like_empty
#array([], dtype=float64)

array([], dtype=float64)

In [ ]:
identity_matrix= numpy.identity(5,dtype='int')
identity_matrix
#array([[1., 0., 0., 0., 0.],
      #  [0., 1., 0., 0., 0.],
      #  [0., 0., 1., 0., 0.],
      #  [0., 0., 0., 1., 0.],
      #  [0., 0., 0., 0., 1.]])

# # array([[1, 0, 0, 0, 0],
#        [0, 1, 0, 0, 0],
#        [0, 0, 1, 0, 0],
#        [0, 0, 0, 1, 0],
#        [0, 0, 0, 0, 1]])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

1.02.2025

Indexing and Slicing

In [ ]:
array_ind = numpy.array(([18,29,38,47],
                        [48,70,60,80],
                        [10,22,39,21]))
array_ind[:] # complete slicing
#array([[18, 29, 38, 47],
      #  [48, 70, 60, 80],
      #  [10, 22, 39, 21]])

array([[18, 29, 38, 47],
       [48, 70, 60, 80],
       [10, 22, 39, 21]])

In [ ]:
array_ind[0]=123
array_ind #replacing the 0th element
# array([[123, 123, 123, 123],
#        [ 48,  70,  60,  80],
#        [ 10,  22,  39,  21]])

array([[123, 123, 123, 123],
       [ 48,  70,  60,  80],
       [ 10,  22,  39,  21]])

In [ ]:
a=numpy.array([[[1],[2],[2]],
              [[9],[7],[4]]]) # should be homogenous

array([[[1],
        [2],
        [2]],

       [[9],
        [7],
        [4]]])

In [ ]:
array_ind[2:,2:]

array([[39, 21]])

In [ ]:
#Accessing the sub matrices.
array_ind[1:,1:3]

# array([[70, 60],
#        [22, 39]])

array([[70, 60],
       [22, 39]])

In [ ]:
array_ind[1:,::3] # row, column
# array([[48, 80],
#        [10, 21]])

array([[48, 80],
       [10, 21]])

In [ ]:
array_ind[1:,::3]=8
array_ind
# array([[123, 123, 123, 123],
#        [ 48,  70,  60,  80],
#        [ 10,  22,  39,  21]])

array([[123, 123, 123, 123],
       [  8,  70,  60,   8],
       [  8,  22,  39,   8]])

3.02.2025
Operations on Arrays:
Arithmetic operations / Bitwise / Logical
1. array with scalar (individual element)
2. array with array
3. Operations using builtin methods.

In [ ]:
numpy_array = numpy.array([33,19,2,3,4])
array_operations = numpy.array([1,1,1,1,0])
numpy_array+=array_operations
numpy_array

array([34, 20,  3,  4,  4])

In [ ]:
numpy_array = numpy.array([33,19,2,3,4])
numpy_array+=3
numpy_array

array([36, 22,  5,  6,  7])

In [ ]:
numpy_array = numpy.array([33,19,2,3,4])-3
numpy_array


array([30, 16, -1,  0,  1])

In [ ]:
numpy_array=numpy.array([33,19,2,3,4])*5
numpy_array

array([165,  95,  10,  15,  20])

In [ ]:
numpy_array=numpy.array([33,19,2,3,4])
numpy_array*20//10


array([66, 38,  4,  6,  8])

In [ ]:
numpy_array&numpy_array
# array([33, 19,  2,  3,  4])

array([33, 19,  2,  3,  4])

In [ ]:
numpy.array([1,2,3])|numpy.array([9,2,3])
# array([9, 2, 3])

array([9, 2, 3])

In [ ]:
numpy.array([89,77,8])>numpy.array([90,2,44])
# array([False,  True, False])

array([False,  True, False])

In [ ]:
n=numpy.array((100,5,99))
n+=22
print(n)
type(n)

[122  27 121]


numpy.ndarray

In [ ]:
import numpy

# Avoid overwriting the 'np' alias for NumPy
numpy_array1 = numpy.array(['String', 'Datatype', 'with', 'Integer'])
numpy_array2 = numpy.array(['integer', 'Datatype', 'with', 'String'])

# Concatenate strings element-wise using numpy.char.add
# result=numpy_array1+ numpy_array2
# print(result)

# ---------------------------------------------------------------------------
# UFuncTypeError                            Traceback (most recent call last)
# <ipython-input-36-5260998f5ff6> in <cell line: 0>()
#       6
#       7 # Concatenate strings element-wise using numpy.char.add
# ----> 8 result =numpy_array1+ numpy_array2
#       9 print(result)

# UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U8'), dtype('<U8')) -> None

In [ ]:
numpy_array = numpy.array([33,19,12,1.3,14]) # constant
numpy_array+=119.3
numpy_array

array([152.3, 138.3, 131.3, 120.6, 133.3])

In [ ]:
numpy_array = numpy.array([33,19,12,1.3,14]) # array
numpy_array+=numpy.array([3.3,19.3,1.2,1.3,1.4])
numpy_array

array([36.3, 38.3, 13.2,  2.6, 15.4])

In [ ]:
numpy_arr = numpy.array([20,13,24,85,60])
print(numpy_arr*2) #[ 40  26  48 170 120]
print(numpy_arr+2)#[22 15 26 87 62]
print(numpy_arr-2) #[18 11 22 83 58]
print(numpy_arr//2) #[10  6 12 42 30]
print(numpy_arr**2)#[ 400  169  576 7225 3600]
print(numpy_arr%2)#[0 1 0 1 0]


[ 40  26  48 170 120]
[22 15 26 87 62]
[18 11 22 83 58]
[10  6 12 42 30]
[ 400  169  576 7225 3600]
[0 1 0 1 0]


In [ ]:
numpy_arr = numpy.array([20,13,24,85,60])
numpy_arr2 = numpy.array([20,9,2,5,6])
# numpy_arr and numpy_arr2 ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
numpy_arr>numpy_arr2#[False  True  True  True  True]
numpy_arr<numpy_arr2 #[False False False False False]
numpy_arr==numpy_arr2 #array([ True, False, False, False, False])
numpy_arr!=numpy_arr2#array([False,  True,  True,  True,  True])


array([False,  True,  True,  True,  True])

In [ ]:
numpy_arr = numpy.array([20,13,24,85,60])
numpy_arr2 = numpy.array([20,9,2,5,6])


In [ ]:
numpy_arr = numpy.array([20,13,24,85,60])
numpy_arr2 = numpy.array([20,9,2,5,6])
numpy.all(numpy_arr==numpy_arr2) #False

False

In [ ]:
numpy_arr = numpy.array([20,13,24,85,60])
numpy_arr2 = numpy.array([20,9,2,5,6])
numpy.all(numpy_arr!=numpy_arr2)

False

4.02.2025
Functions on Arrays.

axis=0 column
axis=1 row

1. concatenate((arr1,arr2))
2. sum(arr)
3. max(arr)
4. min(arr)
5. mean()
6. stack()
7. hstack()
8. vstack()


In [5]:
con_arr1 = numpy.array([1,2,3,4,5])
con_arr2 = numpy.array([6,7,8,9,10])
# list elements should be of same size
#array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]).
numpy.concatenate((con_arr1,con_arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
con_arr1 = numpy.array([[1,2,3,4,5]])
con_arr2 = numpy.array([[6,7,8,9,10]])
# list elements should be of same size
#array([[ 1,  2,  3,  4,  5],
      #  [ 6,  7,  8,  9, 10]])
numpy.concatenate((con_arr1,con_arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
con_arr1 = numpy.array([[1,2,]])
con_arr2 = numpy.array([[6,7]])
# list elements should be of same size
#array([[ 1,  2,  3,  4,  5],
      #  [ 6,  7,  8,  9, 10]])
numpy.concatenate((con_arr1,con_arr2))

array([[1, 2],
       [6, 7]])

In [14]:
con_arr1 = numpy.array([[1,2,3],[4,5,8]])
con_arr2 = numpy.array([[6,7,8],[9,10,9]])
# list elements should be of same size
# array([[ 1,  2,  3],
#        [ 4,  5,  8],
#        [ 6,  7,  8],
#        [ 9, 10,  9]])
numpy.concatenate((con_arr1,con_arr2))

array([[ 1,  2,  3],
       [ 4,  5,  8],
       [ 6,  7,  8],
       [ 9, 10,  9]])

In [16]:
con_arr1 = numpy.array([['HELLO'],[' OW']])
con_arr2 = numpy.array([['YEEKS'],['NOPE']])
# list elements should be of same size
# array([['HELLO'],
#        [' OW'],
#        ['YEEKS'],
#        ['NOPE']], dtype='<U5')
numpy.concatenate((con_arr1,con_arr2))

array([['HELLO'],
       [' OW'],
       ['YEEKS'],
       ['NOPE']], dtype='<U5')

In [34]:
con_arr1 = numpy.array([[[1,2,3],[1,2,3]]])
con_arr2 = numpy.array([[[8,2,2],[2,34,4]]])
woo=numpy.concatenate((con_arr1,con_arr2))
# array([[ 1,  2,  3],
#        [ 1,  2,  3],
#        [ 8,  2,  2],
#        [ 2, 34,  4]])
# woo.shape (4, 3)
# con_arr1.shape (1, 2, 3)

(1, 2, 3)

sum((arr1,arr2),axis=n)


In [18]:
arr1=numpy.array(([1,2,3,4],
                 [2,3,4,5]))
numpy.sum(arr1)
#24

24

In [19]:
arr1=numpy.array(([1,2,3,4],
                 [2,3,4,5]))
numpy.sum(arr1,axis=0)
#array([3, 5, 7, 9])

array([3, 5, 7, 9])

In [20]:
arr1=numpy.array(([1,2,3,4],
                 [2,3,4,5]))
numpy.sum(arr1,axis=1)
#array([10, 14])

array([10, 14])

In [21]:
arr1=numpy.array(([1,2,3,4],
                 [2,3,4,5]))
arr2=numpy.array(([1,2,3,4],
                 [2,3,4,5]))
numpy.sum((arr1,arr2),axis=1)
#array([[3, 5, 7, 9],
      #  [3, 5, 7, 9]])

array([[3, 5, 7, 9],
       [3, 5, 7, 9]])

In [22]:
arr1=numpy.array(([1,2,3,4],
                 [2,3,4,5]))
arr2=numpy.array(([1,2,3,4],
                 [2,3,4,5]))
numpy.sum((arr1,arr2),axis=0)
# array([[ 2,  4,  6,  8],
      #  [ 4,  6,  8, 10]])

array([[ 2,  4,  6,  8],
       [ 4,  6,  8, 10]])

In [24]:
# arr1=numpy.array(([1,2,3,4],
#                  [2,3,4,5],
#                   [6,8,0,0])) >>>> Inhomogenous Value error
# arr2=numpy.array(([1,2,3,4],
#                  [2,3,4,5]))
# numpy.sum((arr1,arr2),axis=0)

In [25]:
arr1=numpy.array([1,2,3,6.2])
arr2=numpy.array([1,2,2.3,4])
numpy.sum((arr1,arr2),axis=0)
# array([ 2. ,  4. ,  5.3, 10.2])

array([ 2. ,  4. ,  5.3, 10.2])

In [28]:
numpy.sum((12,23))
# 35

35

In [36]:
mean_arr=numpy.array([10.890,2097,39776,4098,5988])
numpy.mean(mean_arr)
#10411.8
# 10393.978

10393.978

In [38]:
mean_arr=numpy.array(([10.890,2097,39776,4098,5988],
                     [22,34,40,60,55]))
numpy.mean(mean_arr)

5218.089

In [42]:
numpy_array = numpy.array(([1,2,3,4,5],
                          [20,48,59,69,-7]))
numpy_array2 = numpy.array(([1,2,3,4,5],
                          [2,4,5,6,7]))
numpy.stack((numpy_array,numpy_array2))
#array([[[ 1,  2,  3,  4,  5],
      #   [20, 48, 59, 69, -7]],

      #  [[ 1,  2,  3,  4,  5],
      #   [ 2,  4,  5,  6,  7]]]) #columns

array([[[ 1,  2,  3,  4,  5],
        [20, 48, 59, 69, -7]],

       [[ 1,  2,  3,  4,  5],
        [ 2,  4,  5,  6,  7]]])

In [43]:
numpy_array = numpy.array(([1,2,3,4,5],
                          [20,48,59,69,-7]))
numpy_array2 = numpy.array(([1,2,3,4,5],
                          [2,4,5,6,7]))
numpy.stack((numpy_array,numpy_array2),axis=1)
#array([[[ 1,  2,  3,  4,  5],
      #   [ 1,  2,  3,  4,  5]], #axis =1--rows

      #  [[20, 48, 59, 69, -7],
      #   [ 2,  4,  5,  6,  7]]])

array([[[ 1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5]],

       [[20, 48, 59, 69, -7],
        [ 2,  4,  5,  6,  7]]])

In [45]:
numpy_array = numpy.array(([1,2,3,4,5],
                          [20,48,59,69,-7]))
numpy_array2 = numpy.array(([1,2,3,4,5],
                          [2,4,5,6,7]))
numpy.hstack((numpy_array,numpy_array2))
#array([[[ 1,  2,  3,  4,  5],
      #   [ 1,  2,  3,  4,  5]], #axis =1--rows

      #  [[20, 48, 59, 69, -7],
      #   [ 2,  4,  5,  6,  7]]])

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [20, 48, 59, 69, -7,  2,  4,  5,  6,  7]])

In [46]:
numpy_array = numpy.array(([1,2,3,4,5],
                          [20,48,59,69,-7]))
numpy_array2 = numpy.array(([1,2,3,4,5],
                          [2,4,5,6,7]))
numpy.vstack((numpy_array,numpy_array2))
#array([[[ 1,  2,  3,  4,  5],
      #   [ 1,  2,  3,  4,  5]], #axis =1--rows

      #  [[20, 48, 59, 69, -7],
      #   [ 2,  4,  5,  6,  7]]])

array([[ 1,  2,  3,  4,  5],
       [20, 48, 59, 69, -7],
       [ 1,  2,  3,  4,  5],
       [ 2,  4,  5,  6,  7]])